# fly.toml file generated for securityapp on 2023-08-23T17:29:40-04:00

app = "securityapp"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "scl"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
